### ISSUE TITLE
Problem with Cbc and LAndP cut

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#130]
Issue created by migration from Trac.

Original creator: @ycollet

Original creation time: 2013-08-08 07:07:30

Assignee: @tkralphs

Version: 2.7

I use the last version of Cbc (2.8.3, version number which is not available in the Version drop down menu).
I meet the following problem under Windows (32 + 64) and linux (64).
I added a LAndP cut in Cbc via CbcModel + addCutGenerator.
When I start a resolution (via the Osi Layer of CBC), Cbc hangs.
Here is the gdb log:

#0  0x00000000011d06d0 in CoinIndexedVector::clear (this=0x0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/CoinUtils/src/CoinIndexedVector.cpp:40
#1  0x0000000000eb635d in OsiClpSolverInterface::getBInvARow (this=0x1daca10, row=63, z=0x1da3c40, slack=0x1da3f60)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Clp/src/OsiClp/OsiClpSolverInterface.cpp:5971
#2  0x000000000115c9fe in LAP::CglLandPSimplex::pullTableauRow (this=0x7fffffff90f0, row=...)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cgl/src/CglLandP/CglLandPSimplex.cpp:3128
#3  0x00000000011528ef in LAP::CglLandPSimplex::optimize (this=0x7fffffff90f0, row=63, cut=..., cached=..., params=...)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cgl/src/CglLandP/CglLandPSimplex.cpp:673
#4  0x00000000010e8aa5 in CglLandP::generateCuts (this=0x1c92830, si=..., cs=..., info=...)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cgl/src/CglLandP/CglLandP.cpp:622
#5  0x000000000136e685 in CbcCutGenerator::generateCuts (this=0x1c8de40, cs=..., fullScan=2, solver=0x1aa9b98, node=0x0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcCutGenerator.cpp:306
#6  0x000000000130b7a7 in CbcModel::serialCuts (this=0x1aa9410, theseCuts=..., node=0x0, slackCuts=..., lastNumberCuts=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:9306
#7  0x00000000013066c7 in CbcModel::solveWithCuts (this=0x1aa9410, cuts=..., numberTries=49, node=0x0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:7947
#8  0x00000000012f148d in CbcModel::branchAndBound (this=0x1aa9410, doStatistics=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:2905
#9  0x0000000001276799 in OsiCbcSolverInterface::branchAndBound (this=0x1ba6460)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/OsiCbc/OsiCbcSolverInterface.cpp:787

Best regards,

YC

**Comment by svigerske** [comment]
OsiCbc is not maintained and should not be used. Also we have no way to reproduce.
