### ISSUE TITLE
Problem with Cbc and AllDifferent cut

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#131]
Issue created by migration from Trac.

Original creator: @ycollet

Original creation time: 2013-08-08 07:11:44

Assignee: @tkralphs

Version: 2.7.6

Hello,

I use the last version of Cbc (2.8.3).
I meet the following problem under Windows (32 + 64) and Linux (64).
I added a AllDifferent cut via CbcModel + addCutGenerator. Then I started a resolution using the Osi layer of CBC. Then Cbc hangs.
Here is the gdb log of the problem:

#0  0x00000000010fa29a in CglAllDifferent::generateCuts (this=0x1c959f0, si=..., cs=...)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cgl/src/CglAllDifferent/CglAllDifferent.cpp:99
#1  0x000000000136e685 in CbcCutGenerator::generateCuts (this=0x1c95a80, cs=..., fullScan=2, solver=0x1ba69a8, node=0x0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcCutGenerator.cpp:306
#2  0x000000000130b7a7 in CbcModel::serialCuts (this=0x1ba6220, theseCuts=..., node=0x0, slackCuts=..., lastNumberCuts=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:9306
#3  0x00000000013066c7 in CbcModel::solveWithCuts (this=0x1ba6220, cuts=..., numberTries=49, node=0x0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:7947
#4  0x00000000012f148d in CbcModel::branchAndBound (this=0x1ba6220, doStatistics=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:2905
#5  0x0000000001276799 in OsiCbcSolverInterface::branchAndBound (this=0x1a9d520)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/OsiCbc/OsiCbcSolverInterface.cpp:787

Best regards,

YC

**Comment by svigerske** [comment]
OsiCbc is not maintained and should not be used. Also we have no way to reproduce.
