### ISSUE TITLE
Problem with Cbc and DiveLineSearch Heuristic

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#132]
Issue created by migration from Trac.

Original creator: @ycollet

Original creation time: 2013-08-08 07:17:43

Assignee: @tkralphs

Version: 2.7

Hello,

I met a problem with the divelinesearch heuristic.
I  use the last version of CBC (2.8.3). The problem has been met under windows 32 + 64 and linux 64.

I added the heuristic like this:

CbcHeuristicDiveLineSearch HeuristicDiveLineSearch;

HeuristicDiveLineSearch.setModel(pModel_l);
myCbcModel->addHeuristic(&HeuristicDiveLineSearch);

Here is the gdb log:

#0  0x000000000128f9ba in CbcHeuristicDiveLineSearch::selectVariableToBranch (this=0x1c929e0, solver=0x1cb3a28, newSolution=0x1cb3450, bestColumn=`@`0x7fffffff9d6c: -1, 
    bestRound=`@`0x7fffffff9d70: -1) at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcHeuristicDiveLineSearch.cpp:85
#1  0x0000000001289d6e in CbcHeuristicDive::solution (this=0x1c929e0, solutionValue=`@`0x7fffffffa0b0: 1.0000000000000001e+50, numberNodes=`@`0x7fffffffa020: -1, 
    numberCuts=`@`0x7fffffffa01c: 0, cuts=0x0, nodes=`@`0x7fffffffa030: 0x0, newSolution=0x1cb3450)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcHeuristicDive.cpp:314
#2  0x000000000128c277 in CbcHeuristicDive::solution (this=0x1c929e0, solutionValue=`@`0x7fffffffa0b0: 1.0000000000000001e+50, betterSolution=0x1cb3120)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcHeuristicDive.cpp:902
#3  0x000000000131f576 in CbcModel::doHeuristicsAtRoot (this=0x1aa93e0, deleteHeuristicsAfterwards=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:14322
#4  0x00000000012ef99f in CbcModel::branchAndBound (this=0x1aa93e0, doStatistics=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:2617
#5  0x0000000001276799 in OsiCbcSolverInterface::branchAndBound (this=0x1a9d400)

Best regards,

YC

**Comment by svigerske** [comment]
OsiCbc is not maintained and should not be used. Also we have no way to reproduce.
