### ISSUE TITLE
Problem with Cbc and Dynamic3 Heuristic

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#134]
Issue created by migration from Trac.

Original creator: @ycollet

Original creation time: 2013-08-08 07:24:53

Assignee: @tkralphs

Version: 2.7

Hello,

I use the last version of CBC (2.8.3).
The problem has been met under windows 32 + 64 and linux 64.

I added the Dynamic3 heuristic like this:

CbcHeuristicDynamic3 HeuristicDynamic3;

HeuristicDynamic3.setModel(pModel_l);
myCbcModel->addHeuristic(&HeuristicDynamic3);

Then I started the resolution using the Osi layer of CBC.

Here is the gdb log:

#0  0x00007ffff3471425 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff3474b8b in __GI_abort () at abort.c:91
#2  0x00007ffff346a0ee in __assert_fail_base (fmt=<optimized out>, assertion=0x14ec91b "clpSolver", file=
    0x14ec280 "/home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcLinked.cpp", line=<optimized out>, 
    function=<optimized out>) at assert.c:94
#3  0x00007ffff346a192 in __GI___assert_fail (assertion=0x14ec91b "clpSolver", file=
    0x14ec280 "/home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcLinked.cpp", line=3940, function=
    0x14ee0c0 <CbcHeuristicDynamic3::solution(double&, double*)::__PRETTY_FUNCTION__> "virtual int CbcHeuristicDynamic3::solution(double&, double*)") at assert.c:103
#4  0x00000000012d08dc in CbcHeuristicDynamic3::solution (this=0x1c95a80, solutionValue=`@`0x7fffffffa0b0: 1.0000000000000001e+50, betterSolution=0x1cafe70)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcLinked.cpp:3940
#5  0x000000000131f576 in CbcModel::doHeuristicsAtRoot (this=0x1ba6220, deleteHeuristicsAfterwards=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:14322
#6  0x00000000012ef99f in CbcModel::branchAndBound (this=0x1ba6220, doStatistics=0)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/CbcModel.cpp:2617
#7  0x0000000001276799 in OsiCbcSolverInterface::branchAndBound (this=0x1a9d520)
    at /home/crystal/rmdev/MoteurRiskManager-cmake/build_tmp/Dependencies/Cbc/src/EP_Cbc/Cbc/src/OsiCbc/OsiCbcSolverInterface.cpp:787

Best regards,

YC

**Comment by svigerske** [comment]
OsiCbc is not maintained and should not be used. Also we have no way to reproduce.
