### ISSUE TITLE
strengthen segfaults

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#65]
Issue created by migration from Trac.

Original creator: tuomo

Original creation time: 2009-02-06 09:41:58

Assignee: somebody

Version: 2.0

Keywords: strengthen

from the cbc command line:

Coin Cbc and Clp Solver version 2.20.00, build Jan 20 2009
CoinSolver takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
Coin:import crash.lp
Coin:strengthen
Continuous objective value is 20 - 0.00 seconds
Optimal - objective value 20
Segmentation fault (core dumped)

I attached the lp file.

Best regards
Tuomo

**Comment by svigerske** [comment]
Attachment [crash.lp](https://www.coin-or.org/issue-attachments/Cbc/ticket65/crash.lp) by tuomo created at 2009-02-06 09:42:57

**Comment by svigerske** [comment]
Comment by nowozin created at 2009-02-15 13:05:04

I can reproduce this using Ubuntu 8.10 on x86_64 with a self-compiled version of CBC 2.2.0.

Here is the output:
```
/tmp$ /opt/coin-cbc-2.2.0/bin/cbc -import crash.lp -strengthen
Coin Cbc and Clp Solver version 2.20.00, build Sep 20 2008
command line - /opt/coin-cbc-2.2.0/bin/cbc -import crash.lp -strengthen
Continuous objective value is 20 - 0.03 seconds
Optimal - objective value 20
Segmentation fault
```

and with a recent trunk build the same happens:
```
/tmp$ /opt/coin-osi-trunk20090107/bin/cbc -import crash.lp -strengthen
Coin Cbc and Clp Solver version 2.30.00, build Jan  7 2009
command line - /opt/coin-osi-trunk20090107/bin/cbc -import crash.lp -strengthen (default strategy 1)
Continuous objective value is 20 - 0.01 seconds
Segmentation fault
```

The oldest trunk version I have installed also shows this, so it seems to be a long-standing bug.
```
$ /opt/coin-osi-trunk20080816/bin/cbc -import crash.lp -strengthen
Coin Cbc and Clp Solver version 2.20.00, build Aug 16 2008
command line - /opt/coin-osi-trunk20080816/bin/cbc -import crash.lp -strengthen
Continuous objective value is 20 - 0.02 seconds
Optimal - objective value 20
Segmentation fault
```

GDB trace of 2008/09/15 trunk version for which I have a debug build:
```
$ gdb /opt/coin-osi-trunk20080915-dbg/bin/cbc
GNU gdb 6.8-debian
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu"...
(gdb) run -import crash.lp -strengthen
Starting program: /opt/coin-osi-trunk20080915-dbg/bin/cbc -import crash.lp -strengthen
Coin Cbc and Clp Solver version 2.30.00, build Sep 16 2008
command line - /opt/coin-osi-trunk20080915-dbg/bin/cbc -import crash.lp -strengthen (default strategy 1)
Continuous objective value is 20 - 0.03 seconds

Program received signal SIGSEGV, Segmentation fault.
0x00007fd875c4540c in OsiBabSolver::solutionAddsCuts (this=0x0)
    at /tmp/0/trunk/Osi/src/OsiAuxInfo.hpp:119
119	/tmp/0/trunk/Osi/src/OsiAuxInfo.hpp: No such file or directory.
	in /tmp/0/trunk/Osi/src/OsiAuxInfo.hpp
(gdb) bt
#0  0x00007fd875c4540c in OsiBabSolver::solutionAddsCuts (this=0x0)
    at /tmp/0/trunk/Osi/src/OsiAuxInfo.hpp:119
#1  0x00007fd875c16ee1 in CbcModel::resolve (this=0xdd70b0, parent=0x0, whereFrom=0)
    at CbcModel.cpp:8579
#2  0x00007fd875c28100 in CbcModel::strengthenedModel (this=0xdd70b0) at CbcModel.cpp:11759
#3  0x00007fd875f64b93 in CbcMain1 (argc=4, argv=0x7fff7e3cb7e8, model=`@`0x7fff7e3caf30, 
    callBack=0x7fd875f3e276 <dummyCallBack>) at CbcSolver.cpp:7749
#4  0x00007fd875f70e6a in CbcMain1 (argc=4, argv=0x7fff7e3cb7e8, model=`@`0x7fff7e3caf30)
    at CbcSolver.cpp:3071
#5  0x0000000000401004 in main (argc=4, argv=0x7fff7e3cb7e8) at CoinSolve.cpp:230
(gdb) 
```

**Comment by svigerske** [comment]
Comment by @jjhforrest created at 2009-03-30 16:44:17

probably same as 63 - hopefully now fixed

**Comment by svigerske** [comment]
Comment by @jjhforrest created at 2009-03-30 16:44:17

Resolution: duplicate
