### ISSUE TITLE
Overflow errors on the shapes of my parameters

### ISSUE THREAD

**Issue by chrizandrcouture** [coin-or/Cbc#661]
I'm trying to run an optimisation problem for warehouse routing. [link](https://purehost.bath.ac.uk/ws/portalfiles/portal/227399764/Inventory_routing_in_a_warehouse_The_storage_replenishment_routing_problem.pdf)

I implemented the whole paper in CVXPY over [here](https://github.com/chrizandr/warehouse/blob/main/optim.py)

I keep running into overflow errors on the shape of my variables or constraints.
```
===============================================================================
                                     CVXPY
                                     v1.5.2
===============================================================================
(CVXPY) Aug 01 07:37:29 AM: Your problem has 3172980 variables, 48301 constraints, and 0 parameters.
(CVXPY) Aug 01 07:37:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 01 07:37:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 01 07:37:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Aug 01 07:37:44 AM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
(CVXPY) Aug 01 07:38:02 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Aug 01 07:38:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> GLPK_MI
(CVXPY) Aug 01 07:38:02 AM: Applying reduction Dcp2Cone
(CVXPY) Aug 01 07:40:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Aug 01 07:40:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Aug 01 10:05:37 AM: Applying reduction GLPK_MI
Traceback (most recent call last):
  File "/home/ubuntu/warehouse/optim.py", line 432, in <module>
    optim = SRRP(dataset)
  File "/home/ubuntu/warehouse/optim.py", line 173, in __init__
    self.solve(objective, constraints, vars, intermediate_vars)
  File "/home/ubuntu/warehouse/optim.py", line 419, in solve
    problem.solve(solver=solver, verbose=True)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1073, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py", line 46, in apply
    data, inv_data = super(GLPK_MI, self).apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py", line 114, in apply
    c, d, A, b = problem.apply_parameters()
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 201, in apply_parameters
    self.reduced_A.cache(keep_zeros)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/utilities.py", line 141, in cache
    canonInterface.reduce_problem_data_tensor(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 130, in reduce_problem_data_tensor
    n_constr = A.shape[0] // (n_cols)
OverflowError: Python integer 153258155281 out of bounds for int32
```

Before this I encountered problems in the conic_solver, I fixed that by casting the shape in divmod to int64 instead.
```
===============================================================================
                                     CVXPY
                                     v1.5.2
===============================================================================
(CVXPY) Jul 30 11:49:23 AM: Your problem has 3172980 variables, 48301 constraints, and 0 parameters.
(CVXPY) Jul 30 11:49:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 30 11:49:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 30 11:49:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 30 11:49:38 AM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
(CVXPY) Jul 30 11:49:55 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Jul 30 11:49:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> GLPK_MI
(CVXPY) Jul 30 11:49:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 30 11:52:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 30 11:52:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 30 02:16:59 PM: Applying reduction GLPK_MI
Traceback (most recent call last):
  File "/home/ubuntu/warehouse/optim.py", line 431, in <module>
    # )
  File "/home/ubuntu/warehouse/optim.py", line 173, in __init__
    self.solve(objective, constraints, vars, intermediate_vars)
  File "/home/ubuntu/warehouse/optim.py", line 419, in solve
    problem.solve(solver=solver, verbose=True)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1073, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py", line 46, in apply
    data, inv_data = super(GLPK_MI, self).apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py", line 104, in apply
    problem = self.format_constraints(problem, None)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 264, in format_constraints
    unspecified, remainder = divmod(problem.A.shape[0] *
OverflowError: Python integer 153258155281 out of bounds for int32
```

My question is whether this is a limitation imposed on purpose on these solvers? Is there no way for me to run big optimisation problems like this (3172980 variables, 48301 constraints) in CVXPY.

Can I somehow reduce the number of constraints?

Any help would be appreciated.

**Comment by svigerske** [comment]
153258155281 is 3172980*48301-48301, so either your problem is very dense, or something in CVXPy looks as if it were dense. In the former case, you may have to reduce size to fit the number of nonzeros into the 32-bit integer limit. For the latter case (or in any case, actually), you may want to check with the CVXPy issue tracker (https://github.com/cvxpy/cvxpy/issues).

**Comment by chrizandrcouture** [comment]
@svigerske Thank you for the quick response, my problem is dense and needs that many constraints. What can I do to reduce the size of these constraints? Are there any tools to help me do so or does that mean that the problem needs to be reformulated?

**Comment by svigerske** [comment]
Maybe https://or.stackexchange.com/ would be a proper forum for this question. There is no Cbc issue here.

**Comment by jjhforrest** [comment]
However Clp was designed to work with a large number of elements - by defining CoinBigIndex as long.  The code no longer compiles with that option.  I will fix that - although with a small laptop, it may be difficult to see if it can solve problems with >2**31 elements.

**Comment by svigerske** [comment]
They were using GLPK anyway.

**Comment by chrizandrcouture** [comment]
Got the same issue using CBC, might have copied different stack trace. But yeah I think it is a cvxpy issue not a CBC issue. Thank you all for your help.

**Comment by jjhforrest** [comment]
To see how to solve an LP problem with 3172980 variables and 48301 constraints, take a look at Clp/examples/sprint.cpp.

The idea is simple - you solve a series of problems each with 48301 constraints and say 200,000 variables.
Get a feasible solution - if necessary you can add artificial variables. 
Given that solution price out full model and use best 200,000 variables.
Repeat until no improving reduced costs.

The method was invented for airline problems where you "only" have 1000 constraints but an enormous number of variables.
