### ISSUE TITLE
failure in small IP

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cbc#79]
Issue created by migration from Trac.

Original creator: @mgalati13

Original creation time: 2009-09-09 21:36:06

Assignee: somebody

Version: 

CC:  @mgalati13

The following small IP fails using the CbcMain1 interface. It is a unique case, because all rows and cols are removed by presolver.

http://coral.ie.lehigh.edu/~magh/tmp/subProb.n0.c0.p1.b0.lp
```
        CbcModel cbc(*subprobSI);
        CbcMain0(cbc);
         const char * argv[] = {"cbc","-solve","-quit"};
          CbcMain1(3, argv, cbc);
         
Coin Cbc and Clp Solver version 1.2trunk, build Sep  9 2009
command line - cbc -solve -quit (default strategy 1)
Continuous objective value is 46.6667 - 0.00 seconds
Cgl0003I 20 fixed, 0 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 5 fixed, 0 tightened bounds, 0 strengthened rows, 8 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 0 strengthened rows, 8 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer) and 0 elements
```
gdb gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000003ffa871f6b in free () from /lib64/libc.so.6
(gdb) where
#0  0x0000003ffa871f6b in free () from /lib64/libc.so.6
#1  0x000000000057bc41 in ~CbcRounding (this=0x7fffec90c080)
    at ../../../Cbc/src/CbcHeuristic.cpp:1552
#2  0x00000000004ae837 in doHeuristics (model=0x1d1f3e00, type=1)
    at ../../../Cbc/src/CbcSolver.cpp:3479
#3  0x00000000004c7776 in CbcMain1 (argc=3, argv=0x7fffec9150c0,
    model=`@`0x7fffec914bb0, callBack=0x4a734c <dummyCallBack>)
    at ../../../Cbc/src/CbcSolver.cpp:6680
#4  0x00000000004db968 in CbcMain1 (argc=3, argv=0x7fffec9150c0,
    model=`@`0x7fffec914bb0) at ../../../Cbc/src/CbcSolver.cpp:3099
```

Note, if I run it from the command line using cbc executable, the error does not occur.

```
[magala`@`orclus71 MMKP]$ ~/COIN/coin-Cbc/build-g/bin/cbc subProb.n0.c0.p1.b0.lp
Coin Cbc and Clp Solver version 1.2trunk, build May 27 2009
command line - /users/magala/COIN/coin-Cbc/build-g/bin/cbc subProb.n0.c0.p1.b0.lp (default strategy 1)
Continuous objective value is 46.6667 - 0.00 seconds
Cgl0003I 20 fixed, 0 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 5 fixed, 0 tightened bounds, 0 strengthened rows, 8 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 0 strengthened rows, 8 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 46.6667 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Result - Finished objective 46.66667 after 0 nodes and 0 iterations - took 0.00 seconds (total time 0.01)
Total time 0.01
```

**Comment by svigerske** [comment]
Hmm, I used the following code:
```
#include "OsiClpSolverInterface.hpp"
#include "CbcSolver.hpp"
int main()
{
   OsiClpSolverInterface* subprobSI = new OsiClpSolverInterface();
  subprobSI->readLp("subProb.n0.c0.p1.b0.lp");
           CbcModel cbc(*subprobSI);
        CbcMain0(cbc);
         const char * argv[] = {"cbc","-solve","-quit"};
          CbcMain1(3, argv, cbc);
       }
```
With current Cbc/trunk, this seems to run fine:
```
Welcome to the CBC MILP Solver 
Version: Trunk (unstable) 
Build Date: Mar 11 2019 
Revision Number: 2526 

command line - cbc -solve -quit (default strategy 1)
Continuous objective value is 46.6667 - 0.00 seconds
Cgl0004I processed model has 10 rows, 34 columns (34 integer (34 of which binary)) and 62 elements
Cbc0012I Integer solution of 46.66667 found by DiveCoefficient after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective 46.66667, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 46.6667 to 46.6667
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                46.66667000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00
```
Note, however, that the presolved problem is not empty anymore.

Thus, not sure this is fixed, but at least it isn't reproducible anymore so easily.
